FROM python:3.10-slim as builder

WORKDIR /app

COPY requirements.txt /app/

RUN pip install --user --no-cache-dir -r requirements.txt

FROM python:3.10-slim

WORKDIR /app

COPY --from=builder /root/.local /root/.local
COPY . /app/

ENV PATH=/root/.local/bin:$PATH

CMD ["python", "data_processor.py"]